import Head from "next/head";
import Layout from "../componets/Layout";
import Hero from "../componets/Hero";
import css from "../styles/Home.module.css";
import Services from "../componets/Services";

export default function Home() {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero/>
          <Services/>
        </main>
      </div>
    </Layout>
  );
}

